# Generated by Django 4.2 on 2024-07-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0006_remove_otp_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.ManyToManyField(null=True, related_name='users', to='otp.otp'),
        ),
    ]
