# Generated by Django 4.2 on 2024-07-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='action',
            field=models.CharField(choices=[('ResetPass', 'Reset Password'), ('ChangePass', 'Change Password'), ('Login', 'Login'), ('InviteCode', 'Invitation Code')], max_length=20),
        ),
    ]
