# Generated by Django 4.2 on 2024-07-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_alter_otp_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='user_identifier',
        ),
    ]
