# Generated by Django 4.2 on 2024-07-23 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("otp", "0003_remove_otp_updated_at_remove_otp_user_identifier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otp",
            name="is_used",
        ),
        migrations.AlterField(
            model_name="otp",
            name="action",
            field=models.CharField(
                choices=[
                    ("ResetPass", "Reset Password"),
                    ("ChangePass", "Change Password"),
                    ("Login", "Login"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InviteOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invite_otp", models.CharField(max_length=6)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField()),
            ],
        ),
    ]
