# Generated by Django 4.2 on 2024-07-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0004_remove_otp_is_used_alter_otp_action_inviteotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inviteotp",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
