# Generated by Django 4.2 on 2024-07-24 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0005_remove_otp_is_used_alter_inviteotp_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
    ]
