# Generated by Django 4.2 on 2024-07-24 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('otp', '0006_remove_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(default='c5e1fcee-a6d2-4976-a49c-43da7847246b', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
