# Generated by Django 4.2 on 2024-07-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0007_otp_updated_at_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
