# Generated by Django 4.2 on 2024-07-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("otp", "0008_otp_is_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="user_identifier",
            field=models.CharField(default=1234, max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
