# Generated by Django 4.2 on 2024-08-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0009_otp_user_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='action',
            field=models.CharField(choices=[('ResetPass', 'Reset Password'), ('ChangePass', 'Change Password'), ('Login', 'Login'), ('UserDelete', 'User Deletion')], max_length=20),
        ),
    ]
